version: '3'


volumes:
  redis_data:

services: 
    redis:
        image: redis:alpine
        volumes:
           - redis_data:/data
        expose:
          - 6379
        ports:
          - '6379:6379'
        environment:
          - PORT=8080
          - REDIS_ADDR=redis:6379
          - CAPACITY=100
          - GLOBAL_EXPIRY=500
    proxy:
        build: .
        command:
            sh -c "dep ensure &&
                   go build && 
                   ./go-redis-cache"
        links:
            - redis:redis
        depends_on:
            - redis
        volumes:
            - .:/go/src/github.com/andyguwc/go-redis-cache
        ports:
            - "8080:8080" 
       